services:
  pg:
    image: postgres
    container_name: pg_task
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fast-api:
    build: /fastapi-app/
    restart: always
    depends_on:
      - pg
    ports:
      - 8000:8000

  front:
    build: /vue-app/
    restart: always
    depends_on:
      - fast-api
    ports:
      - 8080:8080

volumes:
  postgres_data:
